### ISSUE TITLE
BaseClient.stream_url doesn't support ssl

### ISSUE THREAD

**Issue by youngm** [cloudfoundry-attic/cfoundry#2]
Our cloud foundry deployment is 100% ssl.  This for the most part works.  One issue we've run into though comes when cf attempts to stream the stage log while staging an application.

I currently have an open issue with the dea project to support exposing file urls over ssl: https://github.com/cloudfoundry/dea_ng/issues/33

We've patched dea locally but ran into another problem with cfoundry where the BaseClient.stream_url method doesn't support https urls.

It would be great if this method supported ssl similar to how HttpFactory.create does.

**Comment by youngm** [comment]
This is the error I get when attempting to stream an https url:

```
EOFError: end of file reached

/home/youngstrommj/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/net/protocol.rb:141:in `read_nonblock'
/home/youngstrommj/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/net/protocol.rb:141:in `rbuf_fill'
/home/youngstrommj/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
/home/youngstrommj/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
/home/youngstrommj/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/net/http.rb:2562:in `read_status_line'
/home/youngstrommj/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/net/http.rb:2551:in `read_new'
/home/youngstrommj/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1319:in `block in transport_request'
/home/youngstrommj/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1316:in `catch'
/home/youngstrommj/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1316:in `transport_request'
/home/youngstrommj/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/net/http.rb:1293:in `request'
rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
cfoundry-1.5.3/lib/cfoundry/baseclient.rb:107:in `block in stream_url'
/home/youngstrommj/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/net/http.rb:745:in `start'
/home/youngstrommj/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/net/http.rb:557:in `start'
cfoundry-1.5.3/lib/cfoundry/baseclient.rb:101:in `stream_url'
cfoundry-1.5.3/lib/cfoundry/v2/client.rb:82:in `stream_url'
cf-1.1.4/lib/cf/cli/app/start.rb:55:in `stream_start_log'
cf-1.1.4/lib/cf/cli/app/start.rb:28:in `block in start'
cf-1.1.4/lib/cf/spacing.rb:40:in `block in spaced'
cf-1.1.4/lib/cf/spacing.rb:38:in `each'
cf-1.1.4/lib/cf/spacing.rb:38:in `spaced'
cf-1.1.4/lib/cf/cli/app/start.rb:17:in `start'
mothership-0.5.1/lib/mothership/base.rb:66:in `run'
mothership-0.5.1/lib/mothership/command.rb:72:in `block in invoke'
cf-1.1.4/lib/manifests/plugin.rb:38:in `call'
cf-1.1.4/lib/manifests/plugin.rb:38:in `wrap_with_optional_name'
cf-1.1.4/lib/manifests/plugin.rb:18:in `block (2 levels) in <class:ManifestsPlugin>'
mothership-0.5.1/lib/mothership/command.rb:82:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:82:in `block (2 levels) in invoke'
mothership-0.5.1/lib/mothership/command.rb:86:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:86:in `invoke'
mothership-0.5.1/lib/mothership/base.rb:73:in `invoke'
cf-1.1.4/lib/cf/cli/app/push/create.rb:88:in `start_app'
cf-1.1.4/lib/cf/cli/app/push.rb:66:in `setup_new_app'
cf-1.1.4/lib/cf/cli/app/push.rb:48:in `push'
mothership-0.5.1/lib/mothership/base.rb:66:in `run'
mothership-0.5.1/lib/mothership/command.rb:72:in `block in invoke'
cf-1.1.4/lib/manifests/plugin.rb:137:in `call'
cf-1.1.4/lib/manifests/plugin.rb:137:in `block in create_and_save_manifest'
mothership-0.5.1/lib/mothership/callbacks.rb:74:in `with_filters'
cf-1.1.4/lib/manifests/plugin.rb:136:in `create_and_save_manifest'
cf-1.1.4/lib/manifests/plugin.rb:75:in `wrap_push'
cf-1.1.4/lib/manifests/plugin.rb:27:in `block in <class:ManifestsPlugin>'
mothership-0.5.1/lib/mothership/command.rb:82:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:82:in `block (2 levels) in invoke'
mothership-0.5.1/lib/mothership/command.rb:86:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:86:in `invoke'
mothership-0.5.1/lib/mothership/base.rb:55:in `execute'
cf-1.1.4/lib/cf/cli.rb:156:in `block (2 levels) in execute'
cf-1.1.4/lib/cf/cli.rb:167:in `save_token_if_it_changes'
cf-1.1.4/lib/cf/cli.rb:155:in `block in execute'
cf-1.1.4/lib/cf/cli.rb:101:in `wrap_errors'
cf-1.1.4/lib/cf/cli.rb:151:in `execute'
mothership-0.5.1/lib/mothership.rb:45:in `start'
cf-1.1.4/bin/cf:13:in `<top (required)>'
```
