### ISSUE TITLE
NameError: uninitialized constant Net::HTTP::Get::Multipart

### ISSUE THREAD

**Issue by brucewoo** [cloudfoundry-attic/cfoundry#26]
NameError: uninitialized constant Net::HTTP::Get::Multipart
rest_client.rb:135:in `const_get'
rest_client.rb:135:in`request_uri'
rest_client.rb:180:in `block in request_uri'
/usr/lib/ruby/1.9.1/net/http.rb:745:in`start'
rest_client.rb:164:in `request_uri'
rest_client.rb:68:in`request'
baseclient.rb:63:in `request_raw'
baseclient.rb:58:in`request'
baseclient.rb:50:in `put'
base.rb:30:in`upload_app'

**Comment by dajulia3** [comment]
Could you please give us some context.... When are you getting this error? What command did you execute?
For future reference, here are some tips on creating issues in a way that lets us help you as quickly and easily as possible. 

Helpful items when trying to reproduce your issue:
- CF release version
- Deployment manifest with all passwords and sensitive data removed in a gist
- If the deploy is failing, a gist with the full ‘bosh task xxxx --debug’ output Passwords-removed
- If a specific app is causing an issue (crashing warden container, running away, etc) it’s best to send the app. If that’s not practical, please include a reasonable way to reproduce the issue.
- Basics of IaaS (e.g vCenter 5.1 with 6x96GB hosts running 300 VMs)
- Log and stack traces if applicable (‘bosh log ’ will download a tar of logs from that job)

**Comment by dajulia3** [comment]
Closing since there is no activity on this issue. Feel free to reopen it if you want to respond with the information requested above.

**Comment by khamroddin** [comment]
hash = {}
if photo_file.present?
  hash["photo" ] = UploadIO.new(photo_file,photo_file.content_type)
end
request = Net::HTTP::Post::Multipart.new(uri.request_uri, hash)

response = http.request(request)

**Throws error:**

NameError (uninitialized constant Net::HTTP::Post::Multipart):
