### ISSUE TITLE
Nil access in auth_token.rb:56 against CF 236

### ISSUE THREAD

**Issue by vlerenc** [cloudfoundry-attic/cfoundry#35]
When updating to CF v236, we noticed the following problem in combination with https://github.com/pivotal-cf/broker-registrar:

```
[stderr]
E, [2016-05-18T05:19:17.339846 #5378] ERROR -- : can't convert nil into an exact number (TypeError)
/var/vcap/data/packages/broker-registrar/46213225d775263932e072a461e524baf0994967.1-ad63b0913a21f7559dce0e6374ec4793184d54c9/vendor/bundle/ruby/2.2.0/gems/cfoundry-4.7.1/lib/cfoundry/auth_token.rb:56:in `at'
/var/vcap/data/packages/broker-registrar/46213225d775263932e072a461e524baf0994967.1-ad63b0913a21f7559dce0e6374ec4793184d54c9/vendor/bundle/ruby/2.2.0/gems/cfoundry-4.7.1/lib/cfoundry/auth_token.rb:56:in `expiration'
/var/vcap/data/packages/broker-registrar/46213225d775263932e072a461e524baf0994967.1-ad63b0913a21f7559dce0e6374ec4793184d54c9/vendor/bundle/ruby/2.2.0/gems/cfoundry-4.7.1/lib/cfoundry/auth_token.rb:60:in `expires_soon?'
/var/vcap/data/packages/broker-registrar/46213225d775263932e072a461e524baf0994967.1-ad63b0913a21f7559dce0e6374ec4793184d54c9/vendor/bundle/ruby/2.2.0/gems/cfoundry-4.7.1/lib/cfoundry/baseclient.rb:137:in `needs_token_refresh?'
/var/vcap/data/packages/broker-registrar/46213225d775263932e072a461e524baf0994967.1-ad63b0913a21f7559dce0e6374ec4793184d54c9/vendor/bundle/ruby/2.2.0/gems/cfoundry-4.7.1/lib/cfoundry/baseclient.rb:82:in `request'
/var/vcap/data/packages/broker-registrar/46213225d775263932e072a461e524baf0994967.1-ad63b0913a21f7559dce0e6374ec4793184d54c9/vendor/bundle/ruby/2.2.0/gems/cfoundry-4.7.1/lib/cfoundry/baseclient.rb:66:in `get'
/
```

Can it be that changes introduced to CF v236, e.g. https://github.com/cloudfoundry/cf-release/releases#identity -> https://github.com/cloudfoundry/uaa/releases/tag/3.3.0 introduced the issue and https://github.com/cloudfoundry-attic/cfoundry/blob/master/lib/cfoundry/auth_token.rb#L56 (`Time.at(token_data[:exp])`) isn't matching anymore?

**Comment by dieucao** [comment]
@vlerenc cfoundry is no longer maintained.
You might try raising this question against the uaa repo.
https://github.com/cloudfoundry/uaa/issues
